#spring:
## REDIS
#  redis:
## Redis数据库索引（默认为0）
#    database: 0
## Redis服务器地址
#    host: localhost
## Redis服务器连接端口
#    port: 6379
## Redis服务器连接密码（默认为空）
#    password: ''
## 连接超时时间（毫秒）
#    timeout: 0
# 连接池最大连接数（使用负值表示没有限制）
#    pool:
#      max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
# 连接池中的最大空闲连接
#      max-idle: 8
# 连接池中的最小空闲连接
#      min-idle: 0

server:
  port: 37927

# actuator info
info:
  author: ken

# actuator config 加载所有的端点/默认只加载了 info / health
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
# 可以关闭制定的端点
#    shutdown:
#      enabled: false