spring:
  redis:
    database: 7
    host: 10.42.1.7
    port: 6379
    password: 123456
    timeout: 60000
    lettuce:
      pool:
        # 最大支持连接，默认8
        max-active: 8
        # 最大阻塞时间，负数表示没有限制
        max-wait: -1
        # 最大空闲连接数
        max-idle: 8
        # 最小空闲连接数
        min-idle: 0

server:
  port: 37927

# actuator info
info:
  author: ken

# actuator config 加载所有的端点/默认只加载了 info / health
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
# 可以关闭制定的端点
#    shutdown:
#      enabled: false